### ISSUE TITLE
face conflict in README instructions with mouse highlight

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#107]
Do you have any idea why the face properties specified as in the `all-the-icons` setup from the README are being overridden by `selectrum-mouse-highlight`? 

Perhaps it'd be best to explain the odd behavior I'm encountering. Using the values for `bibtex-actions-symbols` from that snippet in the README, I get (as expected) that the pdf icon (e.g.) for an entry without a corresponding pdf is displayed in the face `bibtex-actions-icon-dim`. If, however, my mouse happens to be hovering over that entry, the icon is displayed using (I think?) the `default` face: 

Without the pesky mouse hovering over anything: 

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/350504/115130990-4aa91980-9fc2-11eb-8a32-e542d3180553.png">

With the mouse: 

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/350504/115130991-4d0b7380-9fc2-11eb-8aae-1a2b02d7b379.png">

_Originally posted by @apc in https://github.com/bdarcus/bibtex-actions/issues/94#issuecomment-821912392_

**Comment by bdarcus** [comment]
I didn't notice because I never use the mouse with this :-)

Can you try adding a setq for `selectrum-mouse-highlight` and see if you can tweak that to work?

If that doesn't work, we can ping selectrum and vertico devs.

**Comment by bdarcus** [comment]
Actually, I just tested by setting `selectrum-mouse-highlight` to nil, but had no impact.

**Comment by minad** [comment]
I am not using the mouse, so this is low priority for me. I am also not using icons. But the screenshots look beautiful :+1: I like the work you are doing here!

**Comment by bdarcus** [comment]
> I am not using the mouse, so this is low priority for me. 

Me too. But does that suggest you think it's an issue with the completion systems?

> I am also not using icons. But the screenshots look beautiful  I like the work you are doing here!

Thanks! Inspired in part by your work, and help!

**Comment by apc** [comment]
I don't use the mouse either. So perhaps you can help me here. Is there a way of making it so the mouse doesn't, just by virtue of the mouse pointer being where it is, change the faces of anything? I don't have to do anything to the mouse for this to happen: if it so happens that the pointer was right above where a line in the mini buffer shows up, that line gets highlighted whether I like it or not.

**Comment by minad** [comment]
> Me too. But does that suggest you think it's an issue with the completion systems?

Usually face issues are issues with the theme or with the Emacs display engine. Often the completion system doesn't have to do much with this.

**Comment by apc** [comment]
Ok, I guess `mouse-highlight` is the variable I didn’t know about?

**Comment by bdarcus** [comment]
> Usually face issues are issues with the theme or with the Emacs display engine.

OK; good to know.

We're seeing the behavior on two different themes, including (on mine) modus-operandi, which I know has explicit support for selectrum and vertico.

In any case, @apc, you should probably take a look there first, if you want to sort this out?

**Comment by apc** [comment]
I'll keep looking. I tried the `modus` themes and the color change happens with all faces on the mini buffer. When the mouse is over a line, everything on the line is set to the same color as the `default` face. Also, it has nothing to do with `all-the-icons`: I'm using plain old `propertize`

```
(setq bibtex-actions-symbols
        `((pdf . (,(propertize "⌘" 'face `(:foreground ,(face-attribute 'default :foreground))) .
                  ,(propertize "⌘" 'face `(:foreground ,(face-attribute 'default :background)))))
          (note . (,(propertize "✎" 'face `(:foreground ,(face-attribute 'default :foreground))) .
                  ,(propertize "✎" 'face `(:foreground ,(face-attribute 'default :background)))))))

```

This is what it looks like, with `modus-operandi`, when the mouse isn't hovering over the line: 

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/350504/115154769-8d163900-a04a-11eb-83b4-69a01ad760b3.png">

And this is what it looks like when the mouse is hovering (note that the color of `selectrum-prescient-primary-highlight`, for example, changes to the color of the `default` face when the mouse is over the entry. 

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/350504/115154813-c5b61280-a04a-11eb-8af5-0f4a1e69b818.png">

But this doesn't seem to be related to `bibtex-actions` at all. Note the contrast below with something like `consult-line`, for example, again using `modus-operandi`: 

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/350504/115155107-66f19880-a04c-11eb-970e-2a906cfa53d2.png">

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/350504/115155113-6eb13d00-a04c-11eb-8b2e-1a531f2c2371.png">

The puzzling thing is that `selectrum-prescient-mouse-highlight` has all properties set to `unspecified`, so I don't know why it's changing the color of the text. 

```
Face: selectrum-mouse-highlight (sample) (customize this face)

Documentation:
Face used for candidates during mouse hovering.

Defined in ‘selectrum.el’.


           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: unspecified
        Underline: t
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
           Extend: unspecified
          Inherit: selectrum-current-candidate

[back]

``` 

You can close this (again!) as far as I'm concerned.
